# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. 


max_value = 4000000
n1, n2 = 1, 2

solution = 0

while n1 < max_value:

    # Fibonacci seq.
    n1, n2 = n2, n1 + n2
    # if numbers are even
    if n1 % 2 == 0:
        solution += n1

print(solution)