# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae: 
# It can be verified that T285 = P165 = H143 = 40755. 
# Find the next triangle number that is also pentagonal and hexagonal. 
# The page has been left unattended for too long and that link/button is no longer active. Please refresh the page. 
